### ISSUE TITLE
KasmVNC crash after some time for all users - fixes on reboot

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#204]
**Describe the bug**
After some time of running KasmVNC I get authentication failed for all logins. A reboot fixes it.

**System Description**
Provide the output of 
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Linux rd 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**KasmVNC Details**
[kasmvncserver_jammy_1.2.0_amd64.deb](https://github.com/kasmtech/KasmVNC/releases/download/v1.2.0/kasmvncserver_jammy_1.2.0_amd64.deb)

Provide the output of this command.
```
Xvnc KasmVNC 1.2.0.2af2e661e9906b5778644f6e2fbe1f51cebb337a - built Sep 13 2023 23:49:36
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12008000, The X.Org Foundation
```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
use KasmVNC for soem time. not being able to login ater some days.

**Expected behavior**
always being able to login

**Additional context**
security settings in config:
security:
  brute_force_protection:
    blacklist_threshold: 999999
    blacklist_timeout: 1

**Comment by ne0YT** [comment]
where should I check for additional logs?

**Comment by ne0YT** [comment]
this is in the log:
```
XIO:  fatal IO error 4 (Interrupted system call) on X server ":58"
      after 9605 requests (9602 known processed) with 0 events remaining.
```

**Comment by ne0YT** [comment]
It seems to be related to memory usage. can it be that the memory will not be freed if the connections stay alive?

**Comment by ne0YT** [comment]
@mmcclaskey it's not available, I will update it as soon as it happens again

**Comment by ne0YT** [comment]
@mmcclaskey 
It's filling the RAM over time.

**Comment by mmcclaskey** [comment]
Can we get the output of `ps aux`

If you have confirmed that the memory utilization of the `Xvnc` process is increasing over time, you may need to use valgrind or memleax to provide us more information. 

https://github.com/WuBingzheng/memleax

**Comment by tomaszduda23** [comment]
The issue still occurs

```
#0  rfb::VNCServerST::writeUpdate (this=this@entry=0x55d22fc4b2d0)
    at /src/common/rfb/VNCServerST.cxx:1033
#1  0x000055d22da6a405 in rfb::VNCServerST::handleTimeout (
    this=0x55d22fc4b2d0, t=<optimized out>)
    at /src/common/rfb/VNCServerST.cxx:718
#2  0x000055d22da619ca in rfb::Timer::checkTimeouts ()
    at /src/common/rfb/Timer.cxx:71
#3  0x000055d22da66ddb in rfb::VNCServerST::checkTimeouts (
    this=0x55d22fc4b2d0) at /src/common/rfb/VNCServerST.cxx:349
#4  0x000055d22da2958e in XserverDesktop::blockHandler (
    this=0x7f1bc8ddd010, timeout=0x7ffd0f012324) at XserverDesktop.cc:448
#5  0x000055d22da1bdd0 in vncCallBlockHandlers (timeout=0x7ffd0f012324)
    at vncExtInit.cc:356
#6  0x000055d22dade780 in BlockHandler (
    pTimeout=pTimeout@entry=0x7ffd0f012324) at dixutils.c:388
#7  0x000055d22db27a13 in WaitForSomething (are_ready=0) at WaitFor.c:201
#8  0x000055d22dad99c6 in Dispatch () at dispatch.c:421
#9  0x000055d22dadddca in dix_main (argc=26, argv=<optimized out>,
    envp=<optimized out>) at main.c:276
#10 0x00007f1bca88c1ca in __libc_start_call_main (
    main=main@entry=0x55d22d9509b0 <main>, argc=argc@entry=26,
    argv=argv@entry=0x7ffd0f012538)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#11 0x00007f1bca88c28b in __libc_start_main_impl (
    main=0x55d22d9509b0 <main>, argc=26, argv=0x7ffd0f012538,
    init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffd0f012528)
    at ../csu/libc-start.c:360
#12 0x000055d22d952d35 in _start ()
```
