### ISSUE TITLE
Stuck in Log-In loop when using RDP into Ubuntu 24

### ISSUE THREAD

**Issue by codycook96** [kasmtech/KasmVNC#270]
It's entirely possible I'm just uninformed and this is expected behavior - I know Wayland is pretty new but admittedly don't have a full grasp on what Wayland vs X11 truly is. I don't know if we should expect to be able to use RDP regardless or the end system using Wayland truly does matter.

I have an Ubuntu 24 VM which has native RDP configured. This works great from any of my windows machines. However, for some reason when I try to RDP into it using Kasm I am brought to a log in page and cannot advance beyond it. It takes a bit longer before refreshing when I have the password correct so I'm inclined to believe its advancing somewhere along the process and not just failing at log in. I can use Kasm to RDP into Windows VMs without issue,

![image](https://github.com/user-attachments/assets/c2a327fa-0461-4b31-a5c2-c511ac469272)

I get the following error in the log after attempting to connect.

> host: debian
> ingest_date: 202408140627
> application: connection_proxy
> levelname: ERROR
> message
> Request failed with status code 500
> {"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n    at settle (/gclient/node_modules/axios/dist/node/axios.cjs:1967:12)\n    at IncomingMessage.handleStreamEnd (/gclient/node_modules/axios/dist/node/axios.cjs:3066:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at Axios.request (/gclient/node_modules/axios/dist/node/axios.cjs:3877:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.authorizeGuacSession (/gclient/kasm.js:183:13)\n    at async /gclient/server.js:30:21","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.6.7","Content-Length":"1850","Accept-Encoding":"gzip, compress, deflate, br"},"httpsAgent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{"proxy:443::::::::false:::::::::::::":{"type":"Buffer","data":[48,130,5,74,2,1,1,2,2,3,4,4,2,19,2,4,32,108,189,93,46,19,78,123,241,83,158,139,114,132,153,46,29,217,153,252,228,216,2,88,176,8,128,104,39,164,32,232,228,4,48,101,188,179,27,253,189,247,33,242,47,74,219,152,72,84,65,134,139,233,135,58,234,205,152,209,57,67,11,128,240,93,80,145,22,233,127,162,29,254,65,88,198,2,216,249,198,209,34,161,6,2,4,102,188,78,106,162,4,2,2,28,32,163,130,3,211,48,130,3,207,48,130,2,183,160,3,2,1,2,2,20,94,4,239,240,214,248,93,145,144,4,151,118,153,165,202,208,111,217,157,151,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,119,49,11,48,9,6,3,85,4,6,19,2,85,83,49,11,48,9,6,3,85,4,8,12,2,86,65,49,13,48,11,6,3,85,4,7,12,4,78,111,110,101,49,13,48,11,6,3,85,4,10,12,4,78,111,110,101,49,13,48,11,6,3,85,4,11,12,4,68,111,70,117,49,15,48,13,6,3,85,4,3,12,6,100,101,98,105,97,110,49,29,48,27,6,9,42,134,72,134,247,13,1,9,1,22,14,110,111,110,101,64,110,111,110,101,46,110,111,110,101,48,30,23,13,50,51,49,48,48,53,48,53,51,56,51,54,90,23,13,50,56,49,48,48,51,48,53,51,56,51,54,90,48,119,49,11,48,9,6,3,85,4,6,19,2,85,83,49,11,48,9,6,3,85,4,8,12,2,86,65,49,13,48,11,6,3,85,4,7,12,4,78,111,110,101,49,13,48,11,6,3,85,4,10,12,4,78,111,110,101,49,13,48,11,6,3,85,4,11,12,4,68,111,70,117,49,15,48,13,6,3,85,4,3,12,6,100,101,98,105,97,110,49,29,48,27,6,9,42,134,72,134,247,13,1,9,1,22,14,110,111,110,101,64,110,111,110,101,46,110,111,110,101,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,177,79,120,182,188,12,12,77,131,165,181,236,144,66,209,134,118,138,198,120,81,60,160,35,247,153,139,37,109,253,119,60,156,107,124,143,162,248,221,217,202,216,179,231,22,190,77,85,19,113,74,239,51,58,96,147,172,209,23,236,132,9,164,96,165,18,211,76,36,121,58,16,253,109,149,83,80,69,175,153,2,188,87,141,153,72,123,207,109,22,113,103,123,110,218,33,188,155,4,241,132,46,200,169,106,43,166,249,126,64,175,157,152,208,41,187,167,62,79,196,96,223,69,34,178,6,14,17,202,182,249,146,157,133,208,189,242,126,178,7,230,232,148,67,168,61,48,250,81,71,237,84,139,232,232,68,225,36,211,70,123,207,88,151,43,144,11,155,45,210,11,41,245,103,29,84,53,147,197,153,144,201,131,200,227,255,170,88,82,190,53,90,213,93,196,116,148,166,114,240,71,61,124,116,160,129,57,209,221,225,138,201,70,201,55,117,105,164,20,16,234,53,65,153,97,208,3,164,36,3,81,72,220,134,201,163,158,33,42,87,63,75,40,122,99,202,162,215,221,38,62,101,108,76,194,177,2,3,1,0,1,163,83,48,81,48,29,6,3,85,29,14,4,22,4,20,13,45,29,200,201,225,65,153,227,47,119,97,139,194,54,88,252,115,204,76,48,31,6,3,85,29,35,4,24,48,22,128,20,13,45,29,200,201,225,65,153,227,47,119,97,139,194,54,88,252,115,204,76,48,15,6,3,85,29,19,1,1,255,4,5,48,3,1,1,255,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,48,254,149,210,234,75,244,47,230,124,38,38,22,5,241,48,180,167,97,161,0,110,114,45,38,90,38,30,72,195,34,104,125,194,198,126,75,26,175,129,151,125,218,224,65,183,208,65,0,103,66,50,31,21,30,117,168,13,70,220,219,151,137,172,113,150,246,117,219,117,116,209,81,40,79,116,110,125,180,58,23,187,109,21,147,107,59,39,204,119,76,198,119,28,249,255,210,242,169,188,108,218,166,40,183,32,186,230,70,221,48,12,109,229,28,224,167,38,196,73,212,248,8,173,211,219,44,53,39,223,230,110,76,207,61,106,178,202,157,221,103,171,11,129,100,164,155,218,99,151,30,129,53,190,202,31,38,145,203,169,23,97,185,144,125,49,156,6,244,131,216,98,14,103,54,10,44,93,238,111,64,76,162,135,58,47,203,42,231,210,73,20,161,211,249,109,191,218,187,149,43,68,160,249,153,62,115,81,224,181,31,28,213,223,241,166,253,223,214,66,119,185,72,69,41,22,242,21,59,129,8,226,216,126,178,87,86,107,169,156,84,152,56,213,49,177,240,134,186,43,247,136,196,240,33,210,164,2,4,0,165,3,2,1,18,166,7,4,5,112,114,111,120,121,169,4,2,2,0,235,170,129,227,4,129,224,244,236,99,229,61,76,219,26,154,41,254,139,184,24,54,203,23,214,107,139,188,96,116,124,67,172,116,243,188,5,135,181,174,25,143,145,215,239,17,159,198,62,239,195,99,223,116,42,46,179,135,173,218,45,73,89,196,228,141,39,66,99,216,141,166,96,119,12,190,78,77,130,31,81,199,136,219,230,198,252,161,138,100,133,92,49,52,130,195,140,231,173,197,125,127,171,223,219,20,35,242,216,215,163,40,249,151,203,74,236,189,47,208,96,250,224,28,199,93,82,186,203,5,225,169,226,248,255,171,113,118,174,88,242,24,110,64,205,155,180,140,73,19,1,99,137,150,138,48,17,27,207,19,25,241,16,81,17,62,165,68,47,31,225,252,100,27,233,20,40,213,37,22,67,160,53,14,193,153,82,149,47,196,12,237,13,32,64,38,252,137,125,160,54,24,122,233,86,22,51,198,233,22,52,177,14,226,8,253,25,171,150,178,165,100,172,90,56,162,131,123,71,13,245,174,6,2,4,87,57,203,139]},"kasm_proxy:443::::::::false:::::::::::::":{"type":"Buffer","data":[48,130,5,96,2,1,1,2,2,3,4,4,2,19,2,4,32,0,133,121,5,227,26,42,117,132,220,75,4,50,214,33,101,255,249,70,196,160,9,117,94,75,186,88,132,118,114,251,224,4,48,91,178,124,217,115,15,249,189,141,171,172,63,58,121,186,34,111,103,104,74,124,184,211,47,214,1,66,143,4,19,77,222,29,159,219,145,66,21,171,110,91,61,232,54,148,136,119,143,161,6,2,4,102,188,71,31,162,4,2,2,28,32,163,130,3,211,48,130,3,207,48,130,2,183,160,3,2,1,2,2,20,94,4,239,240,214,248,93,145,144,4,151,118,153,165,202,208,111,217,157,151,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,119,49,11,48,9,6,3,85,4,6,19,2,85,83,49,11,48,9,6,3,85,4,8,12,2,86,65,49,13,48,11,6,3,85,4,7,12,4,78,111,110,101,49,13,48,11,6,3,85,4,10,12,4,78,111,110,101,49,13,48,11,6,3,85,4,11,12,4,68,111,70,117,49,15,48,13,6,3,85,4,3,12,6,100,101,98,105,97,110,49,29,48,27,6,9,42,134,72,134,247,13,1,9,1,22,14,110,111,110,101,64,110,111,110,101,46,110,111,110,101,48,30,23,13,50,51,49,48,48,53,48,53,51,56,51,54,90,23,13,50,56,49,48,48,51,48,53,51,56,51,54,90,48,119,49,11,48,9,6,3,85,4,6,19,2,85,83,49,11,48,9,6,3,85,4,8,12,2,86,65,49,13,48,11,6,3,85,4,7,12,4,78,111,110,101,49,13,48,11,6,3,85,4,10,12,4,78,111,110,101,49,13,48,11,6,3,85,4,11,12,4,68,111,70,117,49,15,48,13,6,3,85,4,3,12,6,100,101,98,105,97,110,49,29,48,27,6,9,42,134,72,134,247,13,1,9,1,22,14,110,111,110,101,64,110,111,110,101,46,110,111,110,101,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,177,79,120,182,188,12,12,77,131,165,181,236,144,66,209,134,118,138,198,120,81,60,160,35,247,153,139,37,109,253,119,60,156,107,124,143,162,248,221,217,202,216,179,231,22,190,77,85,19,113,74,239,51,58,96,147,172,209,23,236,132,9,164,96,165,18,211,76,36,121,58,16,253,109,149,83,80,69,175,153,2,188,87,141,153,72,123,207,109,22,113,103,123,110,218,33,188,155,4,241,132,46,200,169,106,43,166,249,126,64,175,157,152,208,41,187,167,62,79,196,96,223,69,34,178,6,14,17,202,182,249,146,157,133,208,189,242,126,178,7,230,232,148,67,168,61,48,250,81,71,237,84,139,232,232,68,225,36,211,70,123,207,88,151,43,144,11,155,45,210,11,41,245,103,29,84,53,147,197,153,144,201,131,200,227,255,170,88,82,190,53,90,213,93,196,116,148,166,114,240,71,61,124,116,160,129,57,209,221,225,138,201,70,201,55,117,105,164,20,16,234,53,65,153,97,208,3,164,36,3,81,72,220,134,201,163,158,33,42,87,63,75,40,122,99,202,162,215,221,38,62,101,108,76,194,177,2,3,1,0,1,163,83,48,81,48,29,6,3,85,29,14,4,22,4,20,13,45,29,200,201,225,65,153,227,47,119,97,139,194,54,88,252,115,204,76,48,31,6,3,85,29,35,4,24,48,22,128,20,13,45,29,200,201,225,65,153,227,47,119,97,139,194,54,88,252,115,204,76,48,15,6,3,85,29,19,1,1,255,4,5,48,3,1,1,255,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,48,254,149,210,234,75,244,47,230,124,38,38,22,5,241,48,180,167,97,161,0,110,114,45,38,90,38,30,72,195,34,104,125,194,198,126,75,26,175,129,151,125,218,224,65,183,208,65,0,103,66,50,31,21,30,117,168,13,70,220,219,151,137,172,113,150,246,117,219,117,116,209,81,40,79,116,110,125,180,58,23,187,109,21,147,107,59,39,204,119,76,198,119,28,249,255,210,242,169,188,108,218,166,40,183,32,186,230,70,221,48,12,109,229,28,224,167,38,196,73,212,248,8,173,211,219,44,53,39,223,230,110,76,207,61,106,178,202,157,221,103,171,11,129,100,164,155,218,99,151,30,129,53,190,202,31,38,145,203,169,23,97,185,144,125,49,156,6,244,131,216,98,14,103,54,10,44,93,238,111,64,76,162,135,58,47,203,42,231,210,73,20,161,211,249,109,191,218,187,149,43,68,160,249,153,62,115,81,224,181,31,28,213,223,241,166,253,223,214,66,119,185,72,69,41,22,242,21,59,129,8,226,216,126,178,87,86,107,169,156,84,152,56,213,49,177,240,134,186,43,247,136,196,240,33,210,164,2,4,0,165,3,2,1,18,166,12,4,10,107,97,115,109,95,112,114,111,120,121,169,4,2,2,1,44,170,129,243,4,129,240,244,236,99,229,61,76,219,26,154,41,254,139,184,24,54,203,200,120,152,77,126,29,205,226,94,105,22,18,243,101,67,52,87,66,35,133,35,77,68,85,70,74,103,167,140,138,30,103,191,139,110,90,51,164,238,110,17,70,16,187,211,83,161,134,16,83,213,116,197,104,50,5,122,3,58,158,133,61,16,8,203,69,55,82,222,101,122,170,166,140,234,127,199,187,172,142,95,162,59,237,212,86,133,202,213,215,7,123,102,129,166,51,41,99,80,84,80,101,211,73,240,227,118,41,179,112,164,219,178,109,27,142,14,60,244,223,15,218,74,179,118,151,191,208,247,68,42,21,146,224,236,43,61,180,159,169,2,183,101,149,161,69,85,121,149,174,48,17,197,32,155,202,120,197,54,147,77,201,173,138,134,22,230,141,13,253,241,215,34,253,245,119,50,2,37,198,17,62,37,144,198,29,255,28,59,198,26,180,251,40,17,126,145,238,77,219,83,46,40,181,148,108,57,124,31,88,18,219,54,241,115,232,168,219,216,44,54,157,80,228,174,7,2,5,0,160,233,74,125]}},"list":["proxy:443::::::::false:::::::::::::","kasm_proxy:443::::::::false:::::::::::::"]}},"method":"post","url":"https://proxy:443/api/guac_auth","data":"{\"username\":\"admin\",\"token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzZXNzaW9uX3Rva2VuX2lkIjoiM2RjMGZkMjctNTEwMi00ZjRjLTk0MjEtYjk2NzU5MWU4YTBmIiwiYXV0aG9yaXphdGlvbnMiOlsxMDAsMjAwXSwiZXhwIjoxNzIzOTA0NzMzfQ.A5A-xMppKA8MBx7KNiKFlhMPkoINjmnqhrw5mIRIfqvruysihFra5um_MDiOT9fdMCi7BY0V-GBO1CwEK62uYHAyqc11hqgIQFpxHHGu5cqCINvrkV6hq72_C04gxdz0viggiSqLo7_h5fBRRpccGpgH4pSsah5Nns1rdYvXQaFHpXXmeKOaa4udpm_d_Az2wcozQl6u1QZthTk7q9ghV0SttuxPWSj_EFYHs4hNLae5FFNaNwLQjX4kyV3ksbGcT78HtLgXDwrLxTZtVbSIP_FbVwz5pUjvwAEoCKTX7voIr674_23cUyY89Jfwd1G32GOp2VuoQDgIeOcgjgVrTVimcViwxt7o8AtJOrxU8qatEx_MkHlCGIGPvXvIokqjfHd1n-IN4PSbvsJBxgFfTXI-iI2mK2z3yybNCRcbkBatoGztexMETjHUlfbEtkDoXjPMDb8B10wEg5APwKyLc1wfeWr5IuJ1A8_jlLzr_MlHboQlpsKFSQ_O8KnQ8zYs7HPvtVgj-L-VjaiJV1XyAphJqFzTaQgWphokqx-gi7gU1H6ffP4uYU1FlmKCfr8hatZ0iDX0nRAQVqlL4L4MhlM3z0fu-Q768kgw700MpcMULvQk3EWetSnxqImNVxbKtEXcMcMzVxgdhAo92uryBYD7iI4gI0WNAJyi5jcaXR4\",\"kasm_id\":\"6283461d6881482c96e2ab9c7c5737a8\",\"kasm_client_key\":\"\",\"service\":\"kasm_guac\",\"auth_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjb25uZWN0aW9uX3Byb3h5X2lkIjoiYTY2YzgyYTAtYTQyYy00NTJmLTk5MGQtOTk3NjRkMDNiYTUxIiwiZXhwIjoxNzU1MTUxMDA5LCJhdXRob3JpemF0aW9ucyI6WzgwXX0.LQST70KmoKJMPzcyztRFTU_Jmz7KGO73DWt-x6vU-BM_kpc2bxzIt3RpJkCruOL5zcvHHEpTVp983SpGOVNlGqcN9kWrJXd85eZ8LDnrvPV1r6n-KblUxjeIRNUpmUP6l1lG4n8ZB6jEWGpobap0UcM7IMeUEZ-TvR0wmjObbryFj-_QKVYpFC9aR33BujmuEwcO09DosGEW6wOpgb91rnxbxg9v1HXjps7YyzSG4EMzbKh3iQiAxy7KhjW2_nTdbkeEDgQt8g8jT9mzACQWaU5l7duXl82fYoZtRgF29nMr3dDqI5kuJYM_1w4o8KUuFC99SCEJyEmQwlcff8U8fISnLGHQzTztxrK4lgRZb8tlTQ0ocEhnaCHPLcNDvzVqpUymKnhkXkpd5syXa4CmGp31o77xUAVzOmNrPo2Gy_D_4pGWGEo2csF5rW4SXi4lRktBq_z_8u31Uit0pdRt_URUkVIGN0Rn27flz22b56WA4L2zt3syeeUAowdkHDb5HZNDgoBOaXUeddNrlwac08NG2rFDGvxtEpmOz6h82Tu8UeYcijFcN_dx-snMKTaOE2erTu114e_FKHEUt8q_8cQtugiJL6I0vBLSPq8LpH0GyjxHNrHYZQ12lPJOOI8z5YAn1iSNGPFXtyris8Zj14BfDBZIJ4BQjA6yjyFvT_U\"}"},"code":"ERR_BAD_RESPONSE","status":500}
> AxiosError: Request failed with status code 500
>     at settle (/gclient/node_modules/axios/dist/node/axios.cjs:1967:12)
>     at IncomingMessage.handleStreamEnd (/gclient/node_modules/axios/dist/node/axios.cjs:3066:11)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1358:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
>     at Axios.request (/gclient/node_modules/axios/dist/node/axios.cjs:3877:41)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Object.authorizeGuacSession (/gclient/kasm.js:183:13)
>     at async /gclient/server.js:30:21

**Comment by codycook96** [comment]
Realized I'm at the wrong repo. Closing
